### ISSUE TITLE
Retired values

### ISSUE THREAD

**Issue by graywh** [kenn/active_flag#12]
Have you given any thought about being able to retire values?  I assume it would just require being able to specify a custom value map instead of building one based on array indices.

**Comment by kenn** [comment]
I'm not sure what you mean by "retire values", will you elaborate with examples?

**Comment by graywh** [comment]
Remove a value from use without needing to update existing values in the db.

Say you start with `%i( a b c d )` and later need to remove `:b`.

Being able to customize the bit-value mapping would also allow changing the order.

**Comment by kenn** [comment]
Then you could rename the label with something like `%i( a noop1 c noop2 )` and stop using those values. I believe it's better because when you debug at a lower level, the order of bit array is maintained.
