### ISSUE TITLE
Do you plan to implement `ActiveFlag::Value#to_h`?

### ISSUE THREAD

**Issue by funwarioisii** [kenn/active_flag#29]
We are using ActiveFlag to manage some permissions.
I am currently implementing an admin page, and I am trying to structure it using Hash to see each flags are active.
So I am checking the keys in the flags to see if the respective flags are up.
For example, using the example in the README, we write

```ruby
class Profile < ActiveRecord::Base
  flag :languages, [:english, :spanish, :chinese, :french, :japanese]]

  def to_hash_language
    Profile.language.keys
               .map { |language| [language, languages.to_a.include?(language)] }
               .to_h
  end
end

profile.languages.set(:spanish)
profile.to_hash_languages # => { english: false, spanish: true, chinese: false, japanese: false }
```

I think it would be very useful if this `Profile#to_hash_language` could be written as `profile.languages.to_h # => { english: false, spanish: true, chinese: false, japanese: false }`. How about it?

**Comment by kenn** [comment]
What is the use case, though?

`ActiveFlag::Value` object is a subclass of Set, and most use case I can come up with are covered with the existing methods from `Set`. If `to_h` was frequently used, it would have been implemented within `Set`.

Reopen with a use case if you still think it's worth a dedicated method!
