### ISSUE TITLE
Addition to README about destructuring arrays in scope methods?

### ISSUE THREAD

**Issue by TheBrockEllis** [kenn/active_flag#30]
I'm been using ActiveFlag for a bit and got into a situation where I was trying to filter search results by flags. The filtering form would return an array of flags that needed to be present on the objects in order to be returned. I am using `where_all_` to filter but ran into troubles feeding the array directly to the method. Maybe I'm a ruby n00b, but it took me a few minutes to figure out I had to destructure the array using the splat operator (`*`).

```
@industries = [ :aerospace, :financial ]
Person.where_all_industries(*@industries) 
```

In the interest of helping out other beginners, would you be interested in a PR that adds a line to the README about this case?  More than happy to submit one if so.

**Comment by kenn** [comment]
Hmm, I would like to keep the README as succinct as possible, and splat is pretty basic stuff, so my call is not adding it. Thanks though!
