### ISSUE TITLE
The list of flags once used can only be appended to

### ISSUE THREAD

**Issue by asanghi** [kenn/active_flag#31]
It might be worth mentioning that once you start using the flags in production, the bit arrays are set and one cant remove an option from the list later on. For example if `chinese` is not a supported language anymore, you cant remove it from the list since the bit values will change and lead to invalid data.

The simplicity of the array to specify list of values is great but it is rigid.

**Comment by kenn** [comment]
Yep, that's a natural consequence of bit vector — if you want a regular enum, there are plenty including https://github.com/kenn/enum_accessor.
